esphome:
  name: t-relay-8

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

wifi:
  ssid: "ssid"
  password: "password"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "T-Relay Fallback Hotspot"
    password: "g8TaLY13NVW6"

switch:
  - platform: gpio
    pin: GPIO33
    name: "Relay #1"
    id: relay1

  - platform: gpio
    pin: GPIO32
    name: "Relay #2"
    id: relay2

  - platform: gpio
    pin: GPIO13
    name: "Relay #3"
    id: relay3

  - platform: gpio
    pin: GPIO12
    name: "Relay #4"
    id: relay4

  - platform: gpio
    pin: GPIO21
    name: "Relay #5"
    id: relay5

  - platform: gpio
    pin: GPIO19
    name: "Relay #6"
    id: relay6

  - platform: gpio
    pin: GPIO18
    name: "Relay #7"
    id: relay7

  - platform: gpio
    pin: GPIO5
    name: "Relay #8"
    id: relay8

captive_portal: